== Note
Seeing the problems that people had redeeming deposits due to problems with the electrum server, I've deployed a forked version of the tbtc dapp that uses alternative electrum servers at https://tbtc-forked-dapp.github.io/

Currently it is using blockstream's server, but I've modified the code and set up a proxy server (see https://github.com/corollari/wss2tcp) to allow it to work with any public electrum server (before it would only work with servers that had websockets enabled, but this is very rare and I couldn't find any).

Finally, if you don't trust me it's pretty easy to audit the forked website and verify that I haven't altered anything important, you only have to check the last diverging commits on this repository. This is because the app is hosted through github pages on a github.io domain and the code build is done on a github action, so as long as you trust github it should be possible to verify that the only changes made to the website are the ones caused by the last commits, which change a very low number of lines.



:toc: macro

= tBTC dApp

toc::[]

== Development

=== Setup

The dApp requires a version of the tbtc.js library corresponding to the
environment being tested on. Versions with version `-pre*` are for the Keep
internal testnet and _will not work_ with Ropsten. For Ropsten, look for
versions of tbtc.js labeled `-rc*` instead. Clones of the`master` branch of
this repository will by default use a `-pre*` version of the tbtc.js library;
this version can be adjusted in the `package.json` file.

=== Run

`npm start` runs the app in the development mode.<br>
Open http://localhost:3000[http://localhost:3000] to view it in the browser.

The page will reload if you make edits. You will also see any lint errors in
the console.

== Docker

To build a Docker image execute:
```sh
docker build . -t tbtc-dapp
```

To run the Docker image execute:
```sh
docker run -p 8080:80 tbtc-dapp
```

This will expose the app under http://localhost:8080[http://localhost:8080].

== Internal Testnet

To access the internal Keep testnet you need to be connected to it via VPN.
Contracts with which the app is interacting are deployed under an address that
depends on the current deployment; the latest `tbtc.js` version with prerelease
id `pre` should point to the deployed version.

=== MetaMask

To use the internal testnet, a custom network must be added to MetaMask:

[cols="1,2"]
|===
| **RPC URL**| `http://eth-tx-node.default.svc.cluster.local:8545`
| **ChainID**| `1101`
|===
